spring.jpa.hibernate.ddl-auto=update
server.port=8080
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER_NAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-stacktrace=never
security.jwt.key.private=firmaDeSeguridad
security.jwt.user.generator=com.foro.api

springdoc.api-docs.enable=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

#para escaner paquetes si se quiere morstrar o no
#springdoc.packagesToScan=nombre
